export const getTopicList = state => state.topicList;
export const getUserDetail = state => state.user;
export const getTopicDetail = state => state.topic;
export const getLoginName = state => state.loginname;
export const getAccessToken = state => state.accesstoken;
export const getAvatarUrl = state => state.avatar_url;
export const getCollectedTopics = state => state.collectedTopics;
export const getNotifications = state => state.notifications;
export const getUnreadNotificationsNum = state => state.unread;
