export const GET_LIST = 'GET_LIST';
export const GET_HISTORIES = 'GET_HISTORIES';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_TOPIC = 'GET_TOPIC';
export const GET_TOPIC_FAILURE = 'GET_TOPIC_FAILURE';
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';